### ISSUE TITLE
All Tests Fail to initiate

### ISSUE THREAD

**Issue by AbhiX28** [aspose-pdf-cloud/aspose-pdf-cloud-node.js#14]
Not sure if you have tried running the tests for this package. They fail to initiate as there's a bug on https://github.com/aspose-pdf-cloud/aspose-pdf-cloud-node.js/blob/master/test/baseTestPdfApi.ts#L23
the correct code should have been `import { AsposeResponse } from "../src/models/asposeResponse";`

**Comment by tilalahmad** [comment]
@AbhiX28 
We have fixed the issue with 19.1.1 hotfix. It should work now. Thanks
