### ISSUE TITLE
putMergeDocuments method fails with Bad Request

### ISSUE THREAD

**Issue by AbhiX28** [aspose-pdf-cloud/aspose-pdf-cloud-node.js#15]
The putMergeDocuments method fails with a `Bad Request`. 
Even the Unit Tests for the method fail with the same result `Bad Request`
Could you please fix this and publish a new version.
The problem seems to be at https://github.com/aspose-pdf-cloud/aspose-pdf-cloud-node.js/blob/master/src/api/api.ts#L12209

Let me know if you need more info.

Thanks

**Comment by tilalahmad** [comment]
@AbhiX28 
We are sorry for your inconvenience. You are facing the issue, because we have updated the Test server to 19.2 version. We are in the process to update the Production server to 19.2 version as well and then will release a new version of SDK in next week. It will resolve the issue.

**Comment by AbhiX28** [comment]
Hi @tilalahmad ,

Is the new 19.2 version released on production. I tried using the node package with version 19.2 `"asposepdfcloud": "^19.2.0"` but still getting the same error as above.
Any ETA to get a fix for this?

Thanks

**Comment by tilalahmad** [comment]
@AbhiX28 
Yes, 19.2.0 is updated on the production. I have installed node package from npmjs.com and used following code without any issue. We will appreciate it if you please share some more details/code here for further investigation.

`const { PdfApi } = require("asposepdfcloud");
const { MergeDocuments }= require("asposepdfcloud/src/models/mergeDocuments");

pdfApi = new PdfApi("xxxx-xxxx-xxxx-xxxx", "xxxxxxxxxxxxxxxxxxxx");
var fs = require('fs');

// Document list from Storage
const names = ["4pages.pdf", "htmltopdf.pdf"];
const resultName = "MergingResult.pdf";
const mergeDocuments = new MergeDocuments();
mergeDocuments.list = []; 
names.forEach( (file) => {
        mergeDocuments.list.push(file);
    });

// Merge PDF Documents
pdfApi.putMergeDocuments(resultName, mergeDocuments, null, null).then((result) => {    
    console.log(result.body.code);    
}).catch(function(err) {
    // Deal with an error
    console.log(err);
});`

**Comment by AbhiX28** [comment]
Thanks @tilalahmad , that worked. I was trying to directly use the 'mergeDocuments' as a list without instantiating it with the 'mergeDocuments model'

Thanks
