### ISSUE TITLE
NPM MODULE BROKE

### ISSUE THREAD

**Issue by debottam31** [aspose-pdf-cloud/aspose-pdf-cloud-node.js#5]
The latest version of the npm module 18,9,0 is not working properly!!
My findings 
- it doesn't contain the Transpiled JS code.
- in package.json it is referring the js code 

Please do fix it and republish it. I could have been a contributor in case it was a code issue.
Also I was facing 'Bad Request' issue while using PdfApi.putCreateDocument(). If it is not fixed with this issue I will figure out a solution and raise a PR
@aspose-andreyn @shahzad-latif @kaferi @rodya0

**Comment by sohail-aspose** [comment]
Thanks for your feedback.

We have fixed the mentioned issues. Revised version 18.9.1 has been released.
https://www.npmjs.com/package/asposepdfcloud

Regarding 'Bad Request' issue while using PdfApi.putCreateDocument() method, we have switched our SDKs to use version 2.0 of Aspose.PDF Cloud API. This new version has several breaking changes. In particular, the set of methods and their signatures has changed. The putCreateDocument() method is one of them. Previously this method was used for two different purposes: to create an empty document and to convert files of various formats to PDF.

In a new version of the API, it is only used to create an empty PDF document. As a result, it has fewer parameters than before.

To convert various formats to PDF, you can now use the following methods: Get[format]InStorageToPdf or Put[format]InStorageToPdf. For example PutHtmlInStorageToPdf().

So the cause of 'Bad Request' error could be that you are using putCreateDocument() to convert files of other formats to PDF which is not this method's responsibility anymore. Please consider using Get[format]InStorageToPdf or Put[format]InStorageToPdf methods instead.

We are working on a new API Reference and will let you know as soon as it gets ready.

**Comment by debottam31** [comment]
Hey!! That is great 👍 
And thanks for the version upgrade info. I will look into the newer method and will seek help from you if required.
Great Job Guys! Learned many things from the code. I am closing this issue

**Comment by sohail-aspose** [comment]
@debottam31 

We would like to let you know that the [API Reference page](https://apireference.aspose.cloud/pdf/) has been updated. Just like the SDKs, now it is using version 2.0 of Aspose.PDF Cloud API.
